name: Run Semgrep

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Semgrep
        run: |
          semgrep \
            --config=auto \
            --config=p/security-audit \
            --config=p/secrets \
            --config=p/golang \
            --sarif \
            --output=semgrep-results.sarif \
            --error \
            --verbose \
            --timeout=300 \
            .

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep
        if: always()

  semgrep-full:
    name: Semgrep Full Registry Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run comprehensive Semgrep scan
        run: |
          semgrep \
            --config=r/go.security \
            --config=r/go.lang.security \
            --config=r/secrets \
            --config=r/generic.secrets \
            --config=r/dockerfile \
            --config=r/yaml \
            --sarif \
            --output=semgrep-full-results.sarif \
            --error \
            --verbose \
            --timeout=600 \
            .

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-full-results.sarif
          category: semgrep-full
        if: always()
